### ISSUE TITLE
请问怎样隔一段时间再发送模板消息？

### ISSUE THREAD

**Issue by leadream** [ifanrx/hydrogen-js-sdk#12]
Hi，你好，我最近在使用知晓云开发小程序，遇到了一个问题：我开发的是一个日程小程序，用户可以订阅一个某一个日程，但是我不想在用户订阅的时候就发送模板消息，而是让用户选择在什么时候发送通知。但是我看了文档没有搞懂该怎样实现，还是说知晓云暂时只支持创建数据时立即发送呢？谢谢解答。

**Comment by YaoKaiLun** [comment]
我们不久后将开放定时任务功能，可以期待一下 ^ _ ^

**Comment by leadream** [comment]
@YaoKaiLun 谢谢，十分期待。

**Comment by heshiyou** [comment]
已提供定时器功能。
