### ISSUE TITLE
使用微信基础库1.9.97或者2.0.9无法加载插件版sdk1.5.0以上版本

### ISSUE THREAD

**Issue by jihao** [ifanrx/hydrogen-js-sdk#33]
微信基础库选择的是1.9.97

1.5.0 可以
![ok](https://user-images.githubusercontent.com/322532/46706704-7e27c200-cc68-11e8-9994-ad83ad2ff63f.PNG)

1.6.0 报错
![1 6 0](https://user-images.githubusercontent.com/322532/46706651-3ef97100-cc68-11e8-9239-f90531f1e084.PNG)

1.8.1报错
![1 8 1](https://user-images.githubusercontent.com/322532/46706653-3ef97100-cc68-11e8-9064-34a3d50f3fd7.PNG)

**Comment by larry011** [comment]
你可以使用文件版 https://doc.minapp.com/js-sdk/download-sdk.html

**Comment by larry011** [comment]
close
